monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!doctrine", "!security", "!deprecation", "!app"]
            app:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.app.log"
                level: debug
                channels: ["app"]
            doctrine:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
                level: info
                channels: ["doctrine"]
            security:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.security.log"
                level: debug
                channels: ["security"]
            deprecation:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.deprecation.log"
                level: debug
                channels: ["deprecation"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@prod: &prod
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                channels: ["!event", "!doctrine", "!security", "!deprecation", "!app"]
            app:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.app.log"
                level: info
                channels: ["app"]
            doctrine:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.doctrine.log"
                level: info
                channels: ["doctrine"]
            security:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.security.log"
                level: info
                channels: ["security"]
            deprecation:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.deprecation.log"
                level: error
                channels: ["deprecation"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@stage: *prod